version: '3'

services:
  database:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME

  web:
    build: .
    environment:
      RAILS_ENV: production
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      SECRET_KEY_BASE: $SECRET_KEY_BASE
    ports:
      - 3000:3000
    depends_on:
      - database
