version: '3'

services:
  database:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
  
  redis:
    image: redis:4-alpine

  web:
    build: .
    environment:
      RAILS_ENV: production
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY_BASE: $SECRET_KEY_BASE
    command: "sh -c \"wait-for-tcp.sh $$REDIS_HOST $$REDIS_PORT && wait-for-tcp.sh $$DB_HOST $$DB_PORT && bundle exec puma\""
    ports:
      - 3000:3000
    depends_on:
      - database
      - redis
  
  worker:
    build: .
    environment:
      RAILS_ENV: production
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY_BASE: $SECRET_KEY_BASE
    depends_on:
      - web
      - redis
    
